volumes:
  pgdata-volume:
  
services:
  titanic_db: 
    build: ./database
    container_name: titanic_db
    ports:
      - 6666:5432
    volumes:
      - pgdata-volume:/var/lib/postgresql/data
    env_file: 
      - ./database/.env

  titanic_api:
    build: ./api
    container_name: titanic_api
    ports:
      - 8080:8000
    env_file:
      - ./api/.env
    depends_on: [titanic_db] 
  titanic_web:
    build: web/
    container_name: titanic_web
    ports:
      - 3030:3000 
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: keycloak
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev 
    volumes:
      - ~/keycloak_data:/opt/keycloak/data/