apiVersion: v1
kind: ConfigMap
metadata:
  name: titanic-db-env
data:
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: titanic

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: titanic-api-env
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "1234"
  POSTGRES_IP: titanic-db
  POSTGRES_PORT: "5432"
