apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: titanic-db
spec:
  selector:
    matchLabels:
      app: titanic-db
  serviceName: "titanic-db"
  replicas: 2
  template:
    metadata:
      labels:
        app: titanic-db
    spec:
      containers:
        - name: titanic-db
          image: barteoo/db-v1
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: titanic-db-env
          volumeMounts:
            - name: pgdata-volume
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: titanic-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: titanic-db
