apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.0.2
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start-dev"]

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
    #  Port na ktorym serwis nasluchuje w klastrze
    # Inne pody lub serwisy będą się z nim łączyć aby uzyskać dostęp do keycloaka
    - port: 8080
      # To port na którym aplikacja wewnątrz kontenera nasłuchuje
      targetPort: 8080
  selector:
    app: keycloak
    # dostępna dla wszystkich węzłów w klastrze
  type: NodePort
