apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titanic-ml
  template:
    metadata:
      labels:
        app: titanic-ml
    spec:
      containers:
        - name: titanic-ml
          image: barteoo/ml-v2
          ports:
            - containerPort: 8765
          envFrom:
            - configMapRef:
                name: titanic-api-env

---
apiVersion: v1
kind: Service
metadata:
  name: titanic-ml
spec:
  ports:
    - port: 8765
      targetPort: 8765
  selector:
    app: titanic-ml
  type: NodePort
